# Generated by Django 2.2 on 2020-08-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
    ]
