# Generated by Django 2.2 on 2020-09-18 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('webapp', '0008_remove_basket_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='sessions.Session', verbose_name='Сессия'),
        ),
    ]
